(import stb-image (chicken blob) srfi-4
	(chicken file)
	(chicken pathname))

(define (write-pgm blob w h)
  (let ((v (blob->u8vector/shared blob)))
    (print "P2")
    (print "# pgm writer by chicken-stb-image test")
    (print w " " h)
    (print 255)
    (do ((y 0 (+ y 1)))
	((>= y h))
      (do ((x 0 (+ x 1)))
	  ((>= x w))
	(display (u8vector-ref v (+ x (* w y))))
	(display " "))
      (newline))))

(define (write-ppm blob w h c)
  (assert (or (= c 3) (= c 4)))
  (let ((v (blob->u8vector/shared blob)))
    (print "P3")
    (print "# ppm writer by chicken-stb-image test")
    (print w " " h)
    (print 255)
    (do ((y 0 (+ y 1)))
	((>= y h))
      (do ((x 0 (+ x 1)))
	  ((>= x w))
	(display (u8vector-ref v (+ 0 (* c x) (* c w y)))) (display " ")
	(display (u8vector-ref v (+ 1 (* c x) (* c w y)))) (display " ")
	(display (u8vector-ref v (+ 2 (* c x) (* c w y)))) (display " "))
      (newline))))

(define (target file #!optional (appending ""))
  (create-directory "out")
  (make-pathname "out" (conc file appending)))

(define (convert file) (system (conc "convert test.png " file)))

(define (testing file)
  (print "testing " file)
  (convert (target file))
  (receive (d w h c)
      (with-input-from-file (target file) read-image)
    (with-output-to-file (conc (target file ".ppm")) (lambda () (write-ppm d w h c))))

  ;; test conversion to grayscale
  (receive (d w h c)
      (with-input-from-file (target file) (lambda () (read-image channels: 1)))
    (with-output-to-file (conc (target file ".pgm")) (lambda () (write-pgm d w h)))))

(testing "test.jpg")
(testing "test.png")
(testing "test.bmp")
(testing "test.tga")
;; (convert "test.hdr") ;; uses eof, so didn't bother with this one yet (load works)

(print "testing hdr (from memory)")
(convert (target "test.hdr"))
(receive (d w h c)
    (load-image (with-input-from-file (target "test.hdr") read-string))
  (with-output-to-file (target "test.hdr" ".ppm") (lambda () (write-ppm d w h c))))

(display "\nExpecting \"unknown image type\" error here: ")
(handle-exceptions e (print-error-message e)
		   (with-input-from-string "bad example" read-image))
